### ISSUE TITLE
FEATURE REQUEST: make num_init_children configurable

### ISSUE THREAD

**Issue by mouchar** [bitnami/bitnami-docker-pgpool#14]
**Description**
Hello,
I'd like to have the setting `num_init_children` configurable, since the default value (32) is a bit low and I'm facing socket queuing issues when multiple pods with Java apps are connecting to pgpool.

When all pgpool children are occupied by connections, the pgpool starts behaving very strangely, because it's not possible to perform a health check and the pod will be eventually killed by kubelet (and all connections are lost).

I'm using the bitnami/postgresql-ha chart, but I believe the change needs to be made here. 
Thanks.

**Comment by andresbono** [comment]
Hi @mouchar, thanks for suggesting this change.

Did you see this section of the README.md? https://github.com/bitnami/bitnami-docker-pgpool#configuration-file

There, it is explained how to mount your own configuration file with whatever options you require in your specific scenario.

---

If you think it's better to enable the `num_init_children` property as an environment variable, would you like to open a PR?

You can follow the example of `PGPOOL_MAX_POOL` as reference:

https://github.com/bitnami/bitnami-docker-pgpool/blob/82d31583c8cce63b05041daf5ab4dd9e65e7afd4/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L47

https://github.com/bitnami/bitnami-docker-pgpool/search?q=PGPOOL_MAX_POOL

Let us know what you think!

**Comment by mouchar** [comment]
Hi, thanks for your suggestion. I am aware of the possibility to mount my own config file. I still consider this option as a last-resort solution. I use your awesome `postgresql-ha` Helm chart and it computes the `backend_hostnameX` values dynamically based on the other parameters (helm release name, replica count, namespace and so on). I would completely lose this functionality if I start using a static config file.
Also, such an important parameter that defines the component scalability really deserves its own env variable.
I will prepare PR, using the same approach as `PGPOOL_MAX_POOL`.

Stay tuned.
:radio:
