### ISSUE TITLE
healthcheck error when using custom PGPOOL_POSTGRES_USERNAME

### ISSUE THREAD

**Issue by nesies** [bitnami/bitnami-docker-pgpool#19]
**Description**

The healtcheck does not work when admin user and datatabase have different names

**Steps to reproduce the issue:**

1. deploy with custom admin user and database (differents eg.: admin and db_admin)
  (i use the helm chart postgresql-ha)
2. wait and look at the pod console

**Describe the results you received:**

A message will pop-up:
```
2020-04-08 08:14:58: pid 106: DETAIL:  database "admin" does not exist
```

And then, the container will be kill/re-created

It comes from the healtcheck script:

```
$ /opt/bitnami/scripts/pgpool/healthcheck.sh 
pgpool 08:10:49.07 INFO  ==> Checking pgpool health...
psql: FATAL:  database "admin" does not exist
```
with some debug:
```
$ bash -x /opt/bitnami/scripts/pgpool/healthcheck.sh 
+ psql -U admin -h localhost -tA -c 'SHOW pool_nodes;'
psql: FATAL:  database "admin" does not exist
```

The healthcheck is running psql with the custom user and by default psql with try to connect to the $USER database, which does not exists.

**Describe the results you expected:**

The healthcheck should target postgres database which always exists

**Comment by andresbono** [comment]
Hi @nesies, thanks for submitting the PR. We will review it shortly.

**Comment by andresbono** [comment]
Hi @nesies, can you use the latest version of the `postgresql-ha` chart and let us know if it works as expected?

**Comment by nesies** [comment]
i deployed version 2.3.1 of the helm chart https://hub.helm.sh/charts/bitnami/postgresql-ha

The healthcheck work like a charm 

thank you


```
1000830000@titi-postgresql-ha-pgpool-5685856b66-6p9cw:/$ 
/opt/bitnami/scripts/pgpool/healthcheck.sh 
pgpool 07:55:51.46 INFO  ==> Checking pgpool health...
```

**Comment by andresbono** [comment]
Great, thanks for confirming!
