### ISSUE TITLE
In pgpool container cannot execute psql

### ISSUE THREAD

**Issue by bjccdsrlcr** [bitnami/bitnami-docker-pgpool#21]
hello. thanks for this tool. 

I launched pgpool using this image. 

And at the same time launched some backend dbs. 

I tried to use show pool_nodes; command to show statee of backend dbs.

but using psql -U pgpool. raise the error following.
![image](https://user-images.githubusercontent.com/30322340/79734057-ad70c200-8328-11ea-933b-b54fd29e1a09.png)

So thanks guyes. I want to know how to uses pgpool commands within the container

**Comment by bjccdsrlcr** [comment]
I think in pgpool this container. there also exists an postgresql. 

I user 7030:5432 docker port to export it. And I can access the db server using my local db client with the ip which is the server ip and port 7030..

but in pgpool container. I cannot access db server using 5432 port. 

thank you for solution.

**Comment by rafariossaa** [comment]
Hi @bjccdsrlcr,
  Could you try using: `psql -U pgpool -h locahost` ?

**Comment by rafariossaa** [comment]
Hi,
 Due to inactivity, I am closing this issue.
 Please, don't hesitate to reopen it if needed.
