### ISSUE TITLE
Running with custom config fails due to missing env variables

### ISSUE THREAD

**Issue by Karimerto** [bitnami/bitnami-docker-pgpool#22]
**Description**

As per instructions in the [README](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/README.md), mounting a custom config is not enough. The startup script first attempts to validate a number of environment variables which do not exist and fails.

**Steps to reproduce the issue:**

1. Simply run the image according to instructions: `docker run -v /my/pool/conf/:/opt/bitnami/pgpool/conf/ bitnami/pgpool`

**Describe the results you received:**

Container will not start
````console
pgpool 08:59:36.88 
pgpool 08:59:36.88 Welcome to the Bitnami pgpool container
pgpool 08:59:36.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 08:59:36.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 08:59:36.88 Send us your feedback at containers@bitnami.com
pgpool 08:59:36.89 
pgpool 08:59:36.89 INFO  ==> ** Starting Pgpool-II setup **
pgpool 08:59:36.91 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 08:59:36.91 ERROR ==> The Pgpool administrator user's credentials are mandatory. Set the environment variables PGPOOL_ADMIN_USERNAME and PGPOOL_ADMIN_PASSWORD with the Pgpool administrator user's credentials.
pgpool 08:59:36.91 ERROR ==> The PostrgreSQL replication credentials are mandatory. Set the environment variables PGPOOL_SR_CHECK_USER and PGPOOL_SR_CHECK_PASSWORD with the PostrgreSQL replication credentials.
pgpool 08:59:36.91 ERROR ==> The administrator's database credentials are required. Set the environment variables PGPOOL_POSTGRES_USERNAME and PGPOOL_POSTGRES_PASSWORD with the administrator's database credentials.
pgpool 08:59:36.92 ERROR ==> The list of backend nodes cannot be empty. Set the environment variable PGPOOL_BACKEND_NODES with a comma separated list of backend nodes.
````

**Describe the results you expected:**

I expected the container to start normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

It is obvious why this happens when looking at the various scripts. The `entrypoint.sh` script calls `setup.sh` which attempts to run `pgpool_validate` and that fails because of the missing env vars. I am not sure how this should be fixed in the long run, but for now I suggest that you at least fix the README with a working example of a custom config.

**Comment by marcosbc** [comment]
Hi @Karimerto, you are right about this. Let us look into this to determine the best way to fix the documentation.

**Comment by marcosbc** [comment]
We have identified some improvements, and are working on getting them published. We expect to release them by EOD.

**Comment by marcosbc** [comment]
Just wanted to let you know that we updated the README with the improvements: https://github.com/bitnami/bitnami-docker-pgpool
