### ISSUE TITLE
Connecting to non-specified postgres database

### ISSUE THREAD

**Issue by andres-farias** [bitnami/bitnami-docker-pgpool#27]
**Description**

When launching a simple configuration for pgpool (1 master, 1 standby), we got an authentication error to a posgresql database that has never been specified. 

**Steps to reproduce the issue:**

When starting this PG-POOL via docker with the following command:

docker run -p 5432:5432 -d --rm --name pg-pool \
--env PGPOOL_BACKEND_NODES=0:localhost:5432,1:localhost:5432 \
--env PGPOOL_SR_CHECK_USER=localhost \
--env PGPOOL_SR_CHECK_PASSWORD=XXX \
--env PGPOOL_ENABLE_LDAP=no \
--env PGPOOL_POSTGRES_USERNAME=localhost \
--env PGPOOL_POSTGRES_PASSWORD=XXX \
--env PGPOOL_ADMIN_USERNAME=localhost \
--env PGPOOL_ADMIN_PASSWORD=localhost \
--env PGPOOL_USER_CONF_FILE=/config/myconf.conf \
--env PGPOOL_PASSWD_FILE=/config/pool_passwd \
--volume /opt/globant/pgpool/config/pgpool-ext.conf:/config/myconf.conf \
--volume /opt/globant/pgpool/config/pgpasswd:/config/pool_passwd \
bitnami/pgpool:latest

and the following additional configuration file:
```
allow_clear_text_frontend_auth = on
log_statement = on
log_per_node_statement = true

backend_weight0 = 0
backend_weight1 = 1000

database_redirect_preference_list = 'localhost:1(1.0)'
load_balance_mode = on
log_destination = 'syslog,stderr'
```

**The results we received:**

2020-08-11 16:36:50: pid 1: DETAIL:  no pg_hba.conf entry for host "localhost", user "localhost", database "localhost", SSL off
2020-08-11 16:36:50: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
**Describe the results you expected:**

we have specified balancing for `localhost` database, but the error shows an attempt to connect to a `posgres` database.

**Version**

- Output of `docker version`:

```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Tue Apr 28 14:43:01 2020
 OS/Arch:         linux/amd64
 Experimental:    false```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
```

- Output of `docker-compose version` (if applicable):

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
NONE

**Comment by joancafom** [comment]
Hi @andres-farias ,

Thanks for your issue! This is more likely something related with the [healthcheck](https://github.com/bitnami/bitnami-docker-pgpool/pull/20) pgpool performs, that requires the existence of a database named "postgres" in the backend nodes (which is extremely likely to happen since we are using PostgreSQL). Do you have this DB in your backend nodes?

Thanks!
