### ISSUE TITLE
pgpool logfile not writing in /opt/bitnami/pgpool/logs

### ISSUE THREAD

**Issue by vasudba** [bitnami/bitnami-docker-pgpool#29]
Hi,

pgpool logfile not writing in /opt/bitnami/pgpool/logs. after starting docker container it created softlink to /dev/stdout, but no logs writing to see connections and errors in pgpool configuration

**Comment by marcosbc** [comment]
Hi @vasudba, the pgpool container logs are written directly to stdout/stderr. It is the best practice for containers as it allows for log collection and analysis with container-native solutions, which would not be possible if the logs were written directly to files.

If you want to change that, you could extend the Dockerfile like this:

```
FROM docker.io/bitnami/pgpool:4.1.3-debian-10-r4

# Remove /dev/stdout symlink
RUN rm /opt/bitnami/pgpool/logs/pgpool.log
# Enable logfile
RUN sed -i -E 's/("\$\{command\}" "\$\{flags\[@\]\}")/\1 > "$PGPOOL_LOG_FILE" 2>\&1/' /opt/bitnami/scripts/pgpool/run.sh
```

Afterwards, build your custom Pgpool image and it should work properly.
