### ISSUE TITLE
Diagnostics for num_init_children saturation

### ISSUE THREAD

**Issue by tombh** [bitnami/bitnami-docker-pgpool#30]
I should preface this by saying that I suspect this is really rather a PGPool issue. I'm just posting here first, as it's how I'm using PGPool, and maybe I've missed something in the docs.

When my applications create too many connections to PGPool I get this liveness probe error:

```
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
```

I should add that even if I run `PGPASSWORD=*** psql -U postgres -h localhost` from the PGPool's container, I get the same error. So it's not this chart's fault.

So my issue is that it's curious, considering how important the `num_init_children` config setting is, that the above error is how an admin discovers connection saturation. On top of which (again certainly more a PGPool issue), there doesn't seem to be an easily scriptable way to get the current connection count. Currently I'm having to `kubectl exec` to get a read out of `SHOW pool_processes` and crudely counting lines with BASH and grep.

If this is just how PGPool is, then no problem. But maybe I'm missing something obvious, or something is missing from the docs.

To reproduce:
Create more connections to PGPool than the `num_init_children` setting.

What do I expect to happen?
Simply that there is better insight into the status of `num_init_children` and its limitations.

Extra information:
It might be relevant that my workload triggers the default limit because my application has hundreds of independent worker applications that can't share connections in the application itself.

**Comment by carrodher** [comment]
Hi, yes it seems something related to how the application itself works more than this Docker image or the chart.

Regarding the `num_init_children` property, it can be adjusted by setting the `PGPOOL_NUM_INIT_CHILDREN` environment variable to the container, by default it is set to 32, but you can modify it. You can find this and other customizable parameters in the ["Configuration" section](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/README.md#configuration) of the README.

**Comment by tombh** [comment]
Thank you. Of course I didn't have a problem changing `num_init_children`, that is well documented. Discovering that `num_init_children` was saturated was what was so challenging.

**Comment by carrodher** [comment]
Yes, I understand your point, I don't know if there is an easy/dynamic way to manage this limit and adjust the parameter according to the real status, let's see if other pgpool users can add their thoughts to this conversation
