### ISSUE TITLE
pgpool pod showing CrashLoopBackOff - logs sed: -e expression #1, char 57: unterminated `s' command

### ISSUE THREAD

**Issue by Danteeswararao** [bitnami/bitnami-docker-pgpool#31]
**Description**
I am running the postgress-ha with helm on my k8 cluster and when started postgresql-ha chart ,i could see PgPool pod is showing CrashLoopBackOff and showing below logs

**Steps to reproduce the issue:**

1. helm install --name my-release postgresql-ha statble/postgresql-ha

**Describe the results you received:**

my-release-postgresql-ha-pgpool-847fd9594-zdqtx   0/1     CrashLoopBackOff   6          8m33s
my-release-postgresql-ha-postgresql-0                       1/2     CrashLoopBackOff   6          8m33s
**Describe the results you expected:**

my-release-postgresql-ha-pgpool-847fd9594-zdqtx   1/1     running  0          8m33s
my-release-postgresql-ha-postgresql-0                       2/2     running  0          8m33s

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```
$ kubectl logs my-release-postgresql-ha-pgpool-847fd9594-zdqtx
pgpool 07:11:02.25
pgpool 07:11:02.25 Welcome to the Bitnami pgpool container
pgpool 07:11:02.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 07:11:02.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 07:11:02.26
pgpool 07:11:02.26 INFO  ==> ** Starting Pgpool-II setup **
pgpool 07:11:02.27 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 07:11:02.29 INFO  ==> Initializing Pgpool-II...
pgpool 07:11:02.29 INFO  ==> Generating pg_hba.conf file...
pgpool 07:11:02.29 INFO  ==> Generating pgpool.conf file...
sed: -e expression #1, char 57: unterminated `s' command

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VirtualBox

**Comment by rafariossaa** [comment]
Hi,
  Which kind of k8s cluster are you running the chart it ? Which version of the chart are you using ?

  Could you enable `debug` and paste the full log ? Maybe it will show useful information.

**Comment by emrekgn** [comment]
Hi, 

I'm having the same issue with the postgresql-ha helm chart (bitnami/postgresql-ha version *13.2.0* and minikube version 1.18.1)
 
Just trying to install with `helm install -f values.yml postgres-release bitnami/postgresql-ha`.
After that `kubectl get pods` show *CrashLoopBackOff* for all of the pods including pgpool. Here is the logs for all of the pods:

* Logs for *postgresql-ha-pgpool-778b4695d9-rczbp* :

```
pgpool 12:45:18.39 
pgpool 12:45:18.40 Welcome to the Bitnami pgpool container
pgpool 12:45:18.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 12:45:18.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 12:45:18.40 
pgpool 12:45:18.40 INFO  ==> ** Starting Pgpool-II setup **
pgpool 12:45:18.45 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 12:45:18.48 INFO  ==> Initializing Pgpool-II...
pgpool 12:45:18.49 INFO  ==> Generating pg_hba.conf file...
pgpool 12:45:18.49 INFO  ==> Generating pgpool.conf file...
sed: -e expression #1, char 59: unterminated `s' command
```

* Logs for *postgresql-ha-postgresql-0* :

```
[2021-03-12 12:45:34] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
[2021-03-12 12:45:34] [INFO] connecting to database "user=repmgr password=secret host=postgres-release-postgresql-ha-postgresql-0.postgres-release-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2021-03-12 12:45:34] [DEBUG] connecting to: "user=repmgr password=secret connect_timeout=5 dbname=repmgr host=postgres-release-postgresql-ha-postgresql-0.postgres-release-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path="
[2021-03-12 12:45:34] [ERROR] connection to database failed
[2021-03-12 12:45:34] [DETAIL] 
FATAL:  password authentication failed for user "repmgr"

[2021-03-12 12:45:34] [DETAIL] attempted to connect using:
  user=repmgr password=secret connect_timeout=5 dbname=repmgr host=postgres-release-postgresql-ha-postgresql-0.postgres-release-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
2021-03-12 12:45:34.395 GMT [161] FATAL:  password authentication failed for user "repmgr"
2021-03-12 12:45:34.395 GMT [161] DETAIL:  Password does not match for user "repmgr".
	Connection matched pg_hba.conf line 1: "host     all            repmgr    0.0.0.0/0    md5"
```

* Logs for *postgresql-ha-postgresql-1* :

```
postgresql-repmgr 12:50:54.09 
postgresql-repmgr 12:50:54.10 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 12:50:54.10 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 12:50:54.10 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 12:50:54.10 
postgresql-repmgr 12:50:54.16 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 12:50:54.19 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 12:50:54.19 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 12:50:54.20 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 12:50:54.25 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 12:50:54.26 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 12:50:54.41 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 12:50:54.42 INFO  ==> Initializing Repmgr...
postgresql-repmgr 12:50:54.43 INFO  ==> Waiting for primary node...
```

* *values.yml* :

```
postgresql:
  existingSecret: postgres-secret
  initdbScriptsCM: postgres-configmap
  repmgrLogLevel: DEBUG
```

* *postgres-secret.yml* :

```
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgresql-password: <encoded pwd>
  repmgr-password: <encoded pwd>
```

I cannot figure out what is wrong, maybe some missing configurations in my values.yml?
Thanks in advance.

**Comment by emrekgn** [comment]
Hello again,

Apparently my problem has nothing to do with the pgpool image but the encoded password with a *newline*.
(maybe, sed should escape the provided string as a minor improvement?)

I suspect @Danteeswararao might have the same problem? If that's the case, then the issue also duplicates [this](https://github.com/bitnami/charts/issues/2563).

Anyway I'm posting this just for reference. Thanks and have a great day!

**Comment by rafariossaa** [comment]
Hi,
  @Danteeswararao , could you confirm that ?
