### ISSUE TITLE
Documentation on pgpool clustering

### ISSUE THREAD

**Issue by FatalCatharsis** [bitnami/bitnami-docker-pgpool#32]
**Description**

Can you provide some example documentation of configuring the watchdog process between pgpool containers for HA? The node hosting pgpool died today and I had some downtime while swarm reloaded it somewhere else.

**Comment by andresbono** [comment]
Hi @FatalCatharsis, are you talking about this feature? https://www.pgpool.net/docs/latest/en/html/example-watchdog.html

We don't enable it by default as specified in the main configuration file:

`/opt/bitnami/pgpool/conf/pgpool.conf
```
use_watchdog = off
```

**Comment by FatalCatharsis** [comment]
I've done a bunch of research since posting this suggestion, but I still haven't found a useful answer to a question that might make this issue moot.

Repmgr is responsible for establishing the master and standby server and orchestrating the stream replication. Since pgpool is not responsible for any other of that and is only responsible for load balancing, do multiple pgpool instances even need to be aware of each other in the cluster? 

If so, I can solve my issue by just scaling the number of pgpool instances with them all being active and be done with it.
But I cannot find anything that definitively outlines when the watchdog service needs to be used.

I asked the same question [on stackoverflow](https://stackoverflow.com/questions/63759570/do-you-need-watchdog-on-pgpool-when-using-repmgr) with no luck.

**Comment by andresbono** [comment]
Hi @FatalCatharsis, what configuration determines which one would be a pgpool active node? Just for reference, in our Helm Chart, https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha, all the pgpool pods are initialized in the same way.

**Comment by FatalCatharsis** [comment]
As far as I can tell from all the pgpool documentation, there is no flag to indicate when a node is active. When the watchdog is active, it apparently is coordinating with the other nodes to elect a "master" kind of like repmgr does with postgresql, but instead among pgpool instances.

From what I've gathered though, it appears that this whole single master system is specifically for the case when pgpool is the one handling the actual replication, but I don't see anything that explicitly mentions what situations that require the watchdog service besides, "when pgpool needs to be highly available". Based on some vague comments in other forums and the way your helm chart is setup, I'm just gonna scale up my instances without watchdog enabled and call it good. It's spooky making these changes without documentation to understand the full repercussions, but in this case I think it's on pgpools part. Thanks for your help!

**Comment by psrcek** [comment]
Well as far as I'm aware the watchdog is used to orchestrate setting up a [virtual ip](https://www.pgpool.net/docs/pgpool-II-3.7.4/en/html/runtime-watchdog-config.html#:~:text=Virtual%20IP%20control) that allows setting up clients like hasura (which doesn't support multi server connection strings as far as I'm aware) to only connect to one ip address. pgpool adds an ip address to the new master node's system network interface and removes it from the failed master node. Is there even a way to support this in docker? Maybe with some CAP_* permissions? Could the bitnami containers somehow add support for this?

**Comment by andresbono** [comment]
I think that would be difficult to implement. Does it make sense to use a load balancer when you can't support multi server connections?

**Comment by fwk1010** [comment]
So it not support [pgpool Watchdog](https://www.pgpool.net/docs/latest/en/html/example-cluster.html) yet? @andresbono
I think single instance for any service is dangerous and unreliable.

**Comment by marcosbc** [comment]
@fwk1010 Unfortunately it is not supported, and we have no plans for it. However, feel free to contribute any changes for supporting it, we'd be happy to help with the review and release of those changes.
