### ISSUE TITLE
ERROR:  failed to authenticate with backend using SCRAM

### ISSUE THREAD

**Issue by hyungmoklee** [bitnami/bitnami-docker-pgpool#39]
Hi,

My team was using the combination of bitnami / bitnami-docker-postgresql-repmgr and bitnami / bitnami-docker-pgpool, but we wanted to include pgRouting to bitnami / bitnami-docker-postgresql-repmgr and made a workaround by updating another compilation which is provided through kartoza / docker-postgis repo. I've updated kartoza / docker-postgis and successfully created Docker image/container. I thought it would work well with bitnami / bitnami-docker-pgpool but faced a problem and trying to find a way to get it sorted out. I got an error in the pgpool container as following:

```
2020-10-19 08:30:13: pid 135: ERROR:  failed to authenticate with backend using SCRAM
2020-10-19 08:30:13: pid 135: DETAIL:  valid password not found
```

Can anyone please advise me in which case that sort of error would happen? I appreciate your comments in advance.

Thanks!

FYI. You can have a look at the changes on the branch feature/repmgr in my repo https://github.com/hyungmoklee/docker-postgis.

**Comment by dani8art** [comment]
It seems like this docker image is using SCRAM for auth https://github.com/hyungmoklee/docker-postgis/blob/07747252b2bf025edb0122df6bf11ca387daa87e/scripts/env-data.sh#L255

and we are using the default one

```
$ docker run -ti --rm bitnami/postgresql cat /opt/bitnami/postgresql/conf/postgresql.conf | grep password_encryption
#password_encryption = md5		# md5 or scram-sha-256
```

**Comment by hyungmoklee** [comment]
@dani8art Hi Daniel, thanks for pointing me to the line. That's very helpful to me. 👍

**Comment by hyungmoklee** [comment]
Thanks for the help. I modified my docker-compose.yml file and it now works like a charm.

FYI, I added a new line like - PASSWORD_AUTHENTICATION=md5.

Let me close the issue.
