### ISSUE TITLE
Pgpool is not working correctly

### ISSUE THREAD

**Issue by smlee729** [bitnami/bitnami-docker-pgpool#4]
I tried some experiments over HA solutions using this image, but failed.
My scenario is that:
1. docker-compose up 
2. restart primary node -> repmgr make failover primary to pg-1
3. when pg-0 restarted, joins network as standby node
4. but pgpool's `show pool_nodes;` shows messed up information.
I don't think it's related to the image, but anyway user should know about this.

**Comment by juan131** [comment]
Hi @smlee729 

Pgpool needs to be restarted to "resync" the information. As you mentioned, it won't consider a node "healthy" even if it's been restarted and it's back again.

In K8s ([PostgreSQL HA chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha)) we fixed this by some readiness/liveness probes that will fail and restart the Pgpool container. Using `docker-compose` you have two alternatives:

- Restart Pgpool container.
- Access the Pgpool container and manually attach the restart backend node: see https://www.pgpool.net/docs/latest/en/html/pcp-attach-node.html

**Comment by smlee729** [comment]
Will check that chart. Thanks!
