### ISSUE TITLE
how to dissalow failover ? 

### ISSUE THREAD

**Issue by smilelikeshit** [bitnami/bitnami-docker-pgpool#44]
**Description**

**Steps to reproduce the issue:**

1. i want to disallow failover on slave node.

**Describe the results you received:**

for disable failover when primary node down.

**Describe the results you expected:**

add envvars DISSALOW_FAILOVER=yes on environment variables 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
lient: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by smilelikeshit** [comment]
hi how to disallow failover using pgpool from bitnami.

**Comment by marcosbc** [comment]
Hi @smilelikeshit, we would like to understand more of your use case. Is there a specific reason you would want secondary nodes not to failover?

In any case, it is not currently supported, but it should be doable by making some changes to the PgPool II container's [`libpgpool.sh`](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L347). Feel free to send a PR updating it to support your use case, we'd be happy to review and helping to release new container images with this feature.
