### ISSUE TITLE
how use empty PGPOOL_SR_CHECK_PASSWORD

### ISSUE THREAD

**Issue by DeoLeung** [bitnami/bitnami-docker-pgpool#46]
PGPOOL_SR_CHECK_PASSWORD is required, but we have a no password user for it, how to set it to `empty`?

I tried something like `PGPOOL_SR_CHECK_PASSWORD: ""` but seems that is can't pass the startup check

**Comment by rafariossaa** [comment]
Hi @DeoLeung ,
  `_SR_XXX` environmen variables are used for the streaming replication.
  Could you take a look to the documentation [here](https://github.com/bitnami/bitnami-docker-pgpool#user-content-setting-up-a-ha-postgresql-cluster-with-pgpool-streaming-replication-and-repmgr) ? 
  Also, you can see an example of what is needed in the [docker-compose example](https://github.com/bitnami/bitnami-docker-pgpool#user-content-using-docker-compose) in the readme or in [the folder](url)
  I hope this helps.
