### ISSUE TITLE
Postgres Replication, Asynchronous or Synchrous?

### ISSUE THREAD

**Issue by adon11** [bitnami/bitnami-docker-pgpool#48]
For an internal project we want to use a potgresql database, we want to enable loadbalancing via pgpool, and would like to know if it's possible to enable loadbalancing with asynchronous replication? A second question: does activating synchronous replication dramatically decrease performance for read/write requests? any additional advices or remarks to take into consideration to establish this architecture?

**Comment by rafariossaa** [comment]
Hi,
  Fist of all I would like to remark that I am not a postgresql expert, so my advice about the performance question is to post it on postgresql forums where they can suggest you which could be the best configuration for your use case.
  In general, there is always a trade of, you balance performance vs reliability. It will be as slow as the slower node writing to disk + the transference time. 
  Before deciding which architecture/configuration to use, the best is to deploy them, simulate the expected load and gather statistics. There is not silver bullet configuration, you will need to know how you application is going to use the database service.
Have into account that, even knowing that, it is not the same when you have to 1000 data that when you have 1 million data, I mean, you will probably need to be monitoring your needs to adapt the architecture during its life.

  Regarding hot to enable asynchronous replication, you can set the `POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=0` to disable synchronous replication.

I hope this helps.
