### ISSUE TITLE
Error on OpenShift deployment

### ISSUE THREAD

**Issue by RashadAnsari** [bitnami/bitnami-docker-pgpool#5]
I tried to run Bitnami `postgresql-ha` chart on `OpenShift` and got this error on `pgpool` deployment:

```
pgpool 16:07:34.34
pgpool 16:07:34.34 Welcome to the Bitnami pgpool container
pgpool 16:07:34.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 16:07:34.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 16:07:34.34 Send us your feedback at containers@bitnami.com
pgpool 16:07:34.43
pgpool 16:07:34.43 INFO  ==> ** Starting Pgpool-II setup **
pgpool 16:07:34.53 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 16:07:34.63 INFO  ==> Initializing Pgpool-II...
pgpool 16:07:34.64 INFO  ==> No injected configuration files found. Creating default config files...
pgpool 16:07:34.64 INFO  ==> Generating pg_hba.conf file...
pgpool 16:07:34.73 INFO  ==> Generating pgpool.conf file...
pgpool 16:07:36.13 INFO  ==> Generating password file for local authentication...
pgpool 16:07:36.14 INFO  ==> Generating password file for pgpool admin user...
/libpgpool.sh: line 390: /opt/bitnami/pgpool/etc/pcp.conf: Permission denied
```

**pgpool docker version**: 4.1.0-debian-9-r24

**Comment by carrodher** [comment]
Some Kubernetes distributions (such as OpenShift) run containers using random UUIDs. This approach is not compatible with root containers, which must always run with the root user’s UUID. In such cases, root-only container images will simply not run and a non-root image is a must.
In the case of pgpool image is root, so it is normal that it doesn't work if the OpenShift cluster was deployed using default options. Let me check if there is any strong reason for this image to be root

**Comment by RashadAnsari** [comment]
> Some Kubernetes distributions (such as OpenShift) run containers using random UUIDs. This approach is not compatible with root containers, which must always run with the root user’s UUID. In such cases, root-only container images will simply not run and a non-root image is a must.
> In the case of pgpool image is root, so it is normal that it doesn't work if the OpenShift cluster was deployed using default options. Let me check if there is any strong reason for this image to be root

Thank you @carrodher.

**Comment by carrodher** [comment]
I just checked with the team, it seems pgpool container image is deployed with root user because is needed to configure LDAP. By default, we develop the images as non-root (for infrastructure assets like databases) but in some cases, there are functional limitations where we should use root to provide some features (i.e. LDAP)

**Comment by RashadAnsari** [comment]
Thank you @carrodher.

Can you say how can I run the `postgresql-ha` chart on my OpenShift?
I don't need to use the LDAP feature.
I disabled this feature but I can't run this chart.

According to your explanation, this image is by default non-root but in some cases have some limitation. Can you say How can I disabled these cases and run this image as a non-root?

**Comment by carrodher** [comment]
It seems postgresql-ha chart has the following configuration as `securityContext`:
```yaml
pgpool:
  securityContext:
    enabled: true
    fsGroup: 0
    runAsUser: 0
```
That is the code block that handles the user/group, in this context, pgpool is root by default (`0 = root`). You can disable it by using `--set pgpool.securityContext.enabled=false` in your `helm install` command (or modifying the _values.yaml_), in this way the pgpool container wouldn't set any `securityContext`. [Here](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#parameters) you can find all the available parameters.

**Comment by sameersbn** [comment]
Please note, currently LDAP cannot be used when running the container as non-root as suggested by @carrodher. So you may explicitly want to also set `ldap.enabled=false`

**Comment by RashadAnsari** [comment]
Thank you @carrodher and @sameersbn.

My problem was not fixed with `--set pgpool.securityContext.fsGroup=1001 --set pgpool.securityContext.runAsUser=1001` and `ldap.enabled=false`.

I forked this repository and after adding some lines to docker files my problem was fixed. I add these lines to docker files:

```
RUN \
    mkdir -p /opt/bitnami/pgpool && \
    chgrp -R 0 /opt/bitnami/pgpool && \
    chmod -R g=u /opt/bitnami/pgpool
```

Can I send a pull request for adding these lines to docker files?

**Comment by sameersbn** [comment]
@RashadAnsari 

> My problem was not fixed with
Can you share the pgpool logs after adding those parameters?

> Can I send a pull request for adding these lines to docker files?

Please do. We really appreciate user contributions

**Comment by RashadAnsari** [comment]
Thank you @sameersbn.

This is `pgpool` logs after adding those lines:

```
pgpool 10:52:54.57
--
  | pgpool 10:52:54.57 Welcome to the Bitnami pgpool container
  | pgpool 10:52:54.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
  | pgpool 10:52:54.58 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
  | pgpool 10:52:54.58 Send us your feedback at containers@bitnami.com
  | pgpool 10:52:54.58
  | pgpool 10:52:54.58 INFO  ==> ** Starting Pgpool-II setup **
  | pgpool 10:52:54.69 INFO  ==> Validating settings in PGPOOL_* env vars...
  | pgpool 10:52:54.87 INFO  ==> Initializing Pgpool-II...
  | pgpool 10:52:54.89 INFO  ==> No injected configuration files found. Creating default config files...
  | pgpool 10:52:54.89 INFO  ==> Generating pg_hba.conf file...
  | pgpool 10:52:54.97 INFO  ==> Generating pgpool.conf file...
  | pgpool 10:52:56.29 INFO  ==> Generating password file for local authentication...
  | pgpool 10:52:56.39 INFO  ==> Generating password file for pgpool admin user...
  | pgpool 10:52:56.47 INFO  ==> ** Pgpool-II setup finished! **
  |  
  | pgpool 10:52:56.57 INFO  ==> ** Starting Pgpool-II **
  | 2019-12-06 10:52:56: pid 1: LOG:  Backend status file /opt/bitnami/pgpool/logs/pgpool_status does not exist
  | 2019-12-06 10:52:56: pid 1: LOG:  memory cache initialized
  | 2019-12-06 10:52:56: pid 1: DETAIL:  memcache blocks :64
  | 2019-12-06 10:52:56: pid 1: LOG:  pool_discard_oid_maps: discarded memqcache oid maps
  | 2019-12-06 10:52:57: pid 1: LOG:  Setting up socket for 0.0.0.0:5432
  | 2019-12-06 10:52:57: pid 1: LOG:  Setting up socket for :::5432
  | 2019-12-06 10:52:57: pid 1: LOG:  find_primary_node_repeatedly: waiting for finding a primary node
  | 2019-12-06 10:52:57: pid 1: LOG:  find_primary_node: primary node is 0
  | 2019-12-06 10:52:57: pid 1: LOG:  find_primary_node: standby node is 1
  | 2019-12-06 10:52:57: pid 138: LOG:  PCP process: 138 started
  | 2019-12-06 10:52:58: pid 1: LOG:  pgpool-II successfully started. version 4.1.0 (karasukiboshi)
  | 2019-12-06 10:52:58: pid 1: LOG:  node status[0]: 1
  | 2019-12-06 10:52:58: pid 1: LOG:  node status[1]: 2
  | 2019-12-06 10:53:03: pid 132: LOG:  md5 authentication successful with frontend
  | 2019-12-06 10:53:03: pid 132: LOG:  pool_reuse_block: blockid: 0
  | 2019-12-06 10:53:03: pid 132: CONTEXT:  while searching system catalog, When relcache is missed
  | 2019-12-06 10:53:08: pid 112: LOG:  md5 authentication successful with frontend
  | 2019-12-06 10:53:13: pid 132: LOG:  md5 authentication successful with frontend
```
