### ISSUE TITLE
Set weights for backend nodes

### ISSUE THREAD

**Issue by minsis** [bitnami/bitnami-docker-pgpool#50]
It would be nice to be able to set the weights manually as well either some other variable or using the PGPOOL_BACKEND_NODES variable.

Maybe something like `PGPOOL_BACKEND_NODES=0:pg-0:5432:w1,1:pg-1:5432:w0` or similar.

**Comment by juan131** [comment]
Hi @minsis 

That should be possible, see:

- https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L356
- https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L364

Try setting: `PGPOOL_BACKEND_NODES=0:pg-0:5432:1,1:pg-1:5432:0`

**Comment by minsis** [comment]
Looks like that worked. Thanks!
