### ISSUE TITLE
Failed to authenticate with backend using SCRAM

### ISSUE THREAD

**Issue by minsis** [bitnami/bitnami-docker-pgpool#51]
Getting these errors with failed auth using SCRAM. The pool_passwd file looks fine and I'm able to use the same configured password to connect to my database from inside the container. I'm not sure what I'm missing here

2021-05-11 16:55:08: pid 150: ERROR:  failed to authenticate with backend using SCRAM
2021-05-11 16:55:08: pid 150: DETAIL:  valid password not found

**Steps to reproduce the issue:**

My variables are defined as: 
```
PGPOOL_BACKEND_NODES=0:node1:5432:1:/pg/data:ALWAYS_PRIMARY,1:node2:5432:0:/pg/data:DISALLOW_TO_FAILOVER
PGPOOL_POSTGRES_USERNAME=myuser
PGPOOL_POSTGRES_PASSWORD=mypass
PGPOOL_ADMIN_USERNAME=myuser
PGPOOL_ADMIN_PASSWORD=mypass
PGPOOL_SR_CHECK_USER=myuser
PGPOOL_SR_CHECK_PASSWORD=mypass
PGPOOL_HEALTH_CHECK_USER=myuser
PGPOOL_HEALTH_CHECK_PASSWORD=mypass
PGPOOL_ENABLE_LOAD_BALANCING=no
PGPOOL_USER_CONF_FILE=/pgpool_custom.conf
```

my custom config file has:
```
fail_over_on_backend_error = no
health_check_period = 0
failover_command  = ''
```

But even without my custom config I still get these issues.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tried different combinations of things and nothing seems to get this to work. Looking in the postgres logs I don't see any failed authentication happening. Even if I disable this with `PGPOOL_ENABLE_POOL_PASSWD=no` I still get errors that it can't find the password file even though in the config its set to `pool_passwd=''`. 

Also, the health checks are working fine and its using the same username/password combo to do that.

**Comment by migruiz4** [comment]
Hi @minsis,

I think the following link might explain what happened in your case: https://dba.stackexchange.com/questions/280342/postgres-files-postgresql-conf-and-pg-hba-conf-which-take-priority

Particularly, I think your case matches this scenario:
- pg_hba is configured with md5 and the password of this account is stored with a scram-sha256 hash (independently of password_encryption), the connection will be rejected.

Pgpool is configured with md5, but the password was created with scram-sha256, so when it tries to connect, the connection is rejected.

Although you change password_encryption, it does not affect passwords that have been already created:
> password_encryption in postgresql.conf tells how to hash a new password when it's changed or a new user is created with a password.
