### ISSUE TITLE
Mixed postgresql version

### ISSUE THREAD

**Issue by foarsitter** [bitnami/bitnami-docker-pgpool#58]
Running `psql --version` inside the pgpool containers tels me version 10 is used. On my server there is a different version running (12). The pgpool faq state that major versions [cannot be mixed](https://www.pgpool.net/mediawiki/index.php/FAQ). Is this an serious issue?

I'm chasing an 'server closed the connection unexpectedly' error and different versions for client and server is a reasons that pops up on stackoverflow.

**Comment by marcosbc** [comment]
Hi @foarsitter, the link you added is mentioning that it is not possible to mix different major versions of PostgreSQL with PgPool for proxying purposes, that does not apply for the PostgreSQL CLI version.

**Comment by foarsitter** [comment]
Thanks for de quick reply, totally missed the fact I was comparing the CLI against PostgreSQL .
