### ISSUE TITLE
pgpool breaks when server is shutdown vs services shutdown

### ISSUE THREAD

**Issue by minsis** [bitnami/bitnami-docker-pgpool#59]
I know this is probably more of a pgpool question than anything, but I'm hoping someone here can answer or maybe point me in a direction.

I have pgpool pointing to two postgresql DB VM's in streaming mode using repmgr. When the *standby* server is completely turned off pgpool just breaks. Even though the primary is up and running just fine, with the server shutdown pgpool just breaks.

With that said. if I just simply shut off the services (repmgr and postgresql) and leave the server up and running, pgpool acts just fine. It knows the standby server is offline and not working but continues to connect to the primary.

Note: repmgr is running on the postgresql servers themselves, not using the pgpool configuration for repmgr.

**Comment by javsalgar** [comment]
So it seems that the issue is when it cannot access the server, right? It definitely seems to me an issue with pgpool itself and worth asking the pgpool devs. In any case, I will leave this open in case someone from the community has some insight on this

**Comment by minsis** [comment]
Thanks.

I think I may have found the issue which is partly (or maybe all) my fault.

For whatever reason I decided I needed a custom conf file to include and one of the params I put in there was overriding PGPOOL_HEALTH_CHECK_PERIOD and setting it to 0 (unlimited). So this send pgpool into a loop waiting for all servers to be online before determining which should be primary. After I removed this it would finally timeout. With your default settings it takes up to 5m to time out. However this seems to be hit or miss as I lowered this to total time to 2m and somehow it ends up taking like 15 seconds. I guess another thing for pgpool devs to figure out.

All this still doesn't quite explain why it would be fine when the server was up but service stopped vs server being completely powered down. Oh well.

**Comment by javsalgar** [comment]
Hi,

When using custom configuration files, it would ignore conflicting values set in the environment variables. This allows the versatility of users to include their own configuration. Please let us know if the pgpool devs provide more information.
