### ISSUE TITLE
Best practice to run in PSP

### ISSUE THREAD

**Issue by horiee** [bitnami/bitnami-docker-pgpool#60]
**Description**
How run this image agains stricly configured kubernetes clusters. Is there some sort of recomendations or examples ?
I was following https://github.com/bitnami/bitnami-docker-nginx/issues/139 to fix issue with /tmp dir being read-only file system but there are other issues as well.

```
pgpool 06:05:57.99 
pgpool 06:05:57.99 Welcome to the Bitnami pgpool container
pgpool 06:05:57.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 06:05:57.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 06:05:57.99 
pgpool 06:05:57.99 INFO  ==> ** Starting Pgpool-II setup **
pgpool 06:05:58.02 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 06:05:58.11 INFO  ==> Initializing Pgpool-II...
pgpool 06:05:58.11 INFO  ==> Generating pg_hba.conf file...
/opt/bitnami/scripts/libpgpool.sh: line 314: /opt/bitnami/pgpool/conf/pool_hba.conf: Read-only file system
```

**Comment by pablogalegoc** [comment]
Hi @horiee!

AFAIK not many apps in our catalog are designed to run on read only filesystems and guides or recommendations would have to be specific for each one. Maybe it can be made to work with workarounds like the one mentioned in the issue but no "best practice" that I'm aware of sorry.
