### ISSUE TITLE
How to use scram with bitnami-pgpool-container

### ISSUE THREAD

**Issue by austonpramodh** [bitnami/bitnami-docker-pgpool#61]
I have Postgres instances set up which use SCRAM for authentication. I would like to use SCRAM authentication on bitnami-pgpool container, Unfortunately, I am not able to figure out how. 

Is it possible to use scram on this container? Or do I really have to downgrade to md5 authentication?

I went through a couple of issues present in the issues section, both of them have seemed to have changed the authentication method to md5.

1. bitnami/bitnami-docker-pgpool/issues/39
2. bitnami/bitnami-docker-pgpool/issues/51

Any help would be really great. Thanks in advance.

**Comment by austonpramodh** [comment]
It seems like md5 is the default for this container. The passwords are converted to md5 and then put into the pool_passwd on startup. I could override the pg_hba and pool_passwd using these env vars -> PGPOOL_USER_HBA_FILE, PGPOOL_PASSWD_FILE. 

Although it would be great to have SCRAM support, Maybe some kind of env variable that would decide if `pgpool_create_pghba`, `pgpool_generate_password_file`, and `pgpool_create_pghba` had to do AES or MD5.

I will try to do it myself and raise a PR, whenever I get some free time.

Thanks. This is can be closed now I guess. 
 
![image](https://user-images.githubusercontent.com/5049050/134806571-ead7375e-f61d-480b-9425-2505a108ecaf.png)
![image](https://user-images.githubusercontent.com/5049050/134806670-f87d44a9-c776-41b5-b488-e8585c59ce5b.png)

**Comment by Mauraza** [comment]
Hi @austonpramodh,

The PR sounds great!. It would be a great contribution.

**Comment by austonpramodh** [comment]
Sure, I will raise a pr soon. Most probably before next weekend. Thanks!
