### ISSUE TITLE
psql: ERROR:  failed to authenticate with backend using md5

### ISSUE THREAD

**Issue by cagy520** [bitnami/bitnami-docker-pgpool#65]
[root@poola ~]# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED        STATUS        PORTS      NAMES
26f866aa3ab3   bitnami/pgpool:latest              "/opt/bitnami/script…"   13 hours ago   Up 13 hours   5432/tcp   pgpool2
524ae02e0bcb   bitnami/postgresql-repmgr:latest   "/opt/bitnami/script…"   13 hours ago   Up 13 hours   5432/tcp   pg-1
e2c03b8e3d27   bitnami/postgresql-repmgr:latest   "/opt/bitnami/script…"   13 hours ago   Up 13 hours   5432/tcp   pg-0
[root@poola ~]# docker run -it --rm \
>   --network my-network \
>   bitnami/postgresql:10 \
>   psql -h pgpool2 -U customuser -d customdatabase
postgresql 01:46:12.89 
postgresql 01:46:12.89 Welcome to the Bitnami postgresql container
postgresql 01:46:12.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 01:46:12.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 01:46:12.90 

**psql: ERROR:  failed to authenticate with backend using md5
DETAIL:  valid password not found**
[root@poola ~]# 

![image](https://user-images.githubusercontent.com/9970419/140445430-d1ced986-c1e8-42d1-b140-f6afa07bf262.png)

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml file you used for deploying the solution?
