### ISSUE TITLE
How do I run containers on different computers?

### ISSUE THREAD

**Issue by cagy520** [bitnami/bitnami-docker-pgpool#67]
How do I run containers on different computers?

This scheme only runs on the same computer

**Comment by marcosbc** [comment]
Hi @cagy520, it is possible for you to run it on different computers. You just need to change the `_HOST` values in docker-compose.yml pointing to an external host which is running the container, with the port exposed so it can be accessible. For example: https://github.com/bitnami/bitnami-docker-pgpool#step-2-launch-2-postgresql-repmgr-containers-to-be-used-as-backend-within-your-network

If you are looking for clustering, I recommend you to take a look into https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha

**Comment by cagy520** [comment]
I want to run the master node on pg-0(192.168.126.158)
Then run 'pg-1' on the slave node (192.168.126.158)

But it failed




`docker run --detach --rm --name pg-0 -p 6432:5432 \
  --env REPMGR_PARTNER_NODES=192.168.126.158,192.168.126.159 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=pg-0 \
  --env REPMGR_PRIMARY_HOST=192.168.126.158 \
  --env REPMGR_PASSWORD=repmgrpass \
  --env POSTGRESQL_POSTGRES_PASSWORD=adminpassword \
  --env POSTGRESQL_USERNAME=customuser \
  --env POSTGRESQL_PASSWORD=custompassword \
  --env POSTGRESQL_DATABASE=customdatabase \
  bitnami/postgresql-repmgr:latest
  
docker run --detach --rm --name pg-1 -p 6432:5432 \
  --env REPMGR_PARTNER_NODES=192.168.126.158,192.168.126.159 \
  --env REPMGR_NODE_NAME=pg-1 \
  --env REPMGR_NODE_NETWORK_NAME=pg-1 \
  --env REPMGR_PRIMARY_HOST=192.168.126.158 \
  --env REPMGR_PASSWORD=repmgrpass \
  --env POSTGRESQL_POSTGRES_PASSWORD=adminpassword \
  --env POSTGRESQL_USERNAME=customuser \
  --env POSTGRESQL_PASSWORD=custompassword \
  --env POSTGRESQL_DATABASE=customdatabase \
  bitnami/postgresql-repmgr:latest


docker run --detach --rm --name pgpool -p 9999:5432 \
  --env PGPOOL_BACKEND_NODES=0:192.168.126.158:6432,1:192.168.126.159:6432 \
  --env PGPOOL_SR_CHECK_USER=customuser \
  --env PGPOOL_SR_CHECK_PASSWORD=custompassword \
  --env PGPOOL_ENABLE_LDAP=no \
  --env PGPOOL_POSTGRES_USERNAME=postgres \
  --env PGPOOL_POSTGRES_PASSWORD=adminpassword \
  --env PGPOOL_ADMIN_USERNAME=admin \
  --env PGPOOL_ADMIN_PASSWORD=adminpassword \
  bitnami/pgpool:latest`

**Comment by marcosbc** [comment]
@cagy520 Could you share the errors you get?

**Comment by cagy520** [comment]
> @cagy520 Could you share the errors you get?

![image](https://user-images.githubusercontent.com/9970419/142386686-afd96542-3dc4-4717-ac11-a0aa7c5a6ed8.png)
`postgresql-repmgr 09:17:25.93 
postgresql-repmgr 09:17:25.94 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 09:17:25.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:17:25.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:17:25.94 
postgresql-repmgr 09:17:25.98 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 09:17:26.01 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 09:17:26.01 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 09:17:26.02 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 09:17:26.12 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 09:17:26.13 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 09:17:26.27 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:17:26.29 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:17:26.30 INFO  ==> Waiting for primary node...
`
After about 30 seconds, docker automatically exits

![image](https://user-images.githubusercontent.com/9970419/142386964-67d959be-4cf4-46a1-a1c1-418f90d107e7.png)

**Comment by marcosbc** [comment]
Hi @cagy520, you can find the failing logic [here](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/14/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L519). If you enable the environment variable `BITNAMI_DEBUG=true` it will show you more information, in particular which node it is failing to connect to, which may help you in identifying why it is failing.
