### ISSUE TITLE
`/dev/random` calls hanging pgpool during environment variable evaluation

### ISSUE THREAD

**Issue by conzetti** [bitnami/bitnami-docker-pgpool#70]
---
**Description**

The changes introduced in #63 for scram authentication require calls to `/dev/random` when environment variables are defined/exported. Namely, the environment variable `PGPOOL_AES_KEY` will check to see if the variable is defined but will _default_ to grabbing random data from `/dev/random` and base64 encoding it.

Since dependent Helm charts (e.g. `bitnami/postgresql-ha`) evaluate the environment variables during liveness probe executions, `head -c 20 /dev/random` is called **every** time the liveness probe runs. If enough entropy isn't available, this will cause the container to fail. 

**Although the helm-chart is a separate project, the changes in #63 cause entropy exhaustion from the unnecessary calls to `/dev/random` on variable assignment**

---
**Steps to reproduce the issue:**

1. Deploy `bitnami/postgrsql-ha` chart
2. Run `kubectl get pods` to witness the `pgpool` pods restarting
3. Run` kubectl describe pod postgresql-ha-pgpool-<UUID>` to view the pod status and subsequently failed liveness probe
4. Wait for Pod to come back online
5. Run `kubectl exec -it postgresql-ha-pgpool-<UUID> -- ps aux | grep random` to see the hung process

---
**Describe the results you received:**

`pgpool` Pods restart regularly. In our environment, the Pods are restarting after about 4-5 minutes. This is an AWS environment, and typical deployments are consuming `m5.large` Kubernetes worker nodes. 

**Describe the results you expected:**
`pgpool` Pods don't restart.

**Comment by conzetti** [comment]
For the time being, we're leveraging a `YTT` overlay during the deployment process to inject `PGPOOL_AES_KEY` with phony data. It seems more realistic to identify a cleaner path forward to introducing the `PGPOOL_AES_KEY` and taking into account dependent charts.

**Comment by Mauraza** [comment]
Hi @conzetti,

I have not been able to reproduce the issue. Could you share your values and the logs?

**Comment by conzetti** [comment]
@Mauraza entropy is exhausted and there aren't additional logs. This is only visible when you're absorbing the image in a chart that runs the evaluation against the heredoc of environment variables on a routine basis. I can commit to the `bitnami/postgresql-ha` chart to set a sane default instead of scraping `/dev/random`, but it's troublesome to expect to run this regularly. For example, we shouldn't be rendering random data for an environment variable over and over - there should be a sane default that can be overridden elsewhere.

**Comment by Mauraza** [comment]
Hi @conzetti,

as you have been able to see we are open to a contribution if you want to create a PR with an alternative we will happily review it!

**Comment by rafariossaa** [comment]
Hi,
  I am creating an internal task to find the best approach to fix this. We will come back a soon as possible.
  Meanwhile, as @Mauraza , if you want to send a PR we will be glad to review and merge it.

**Comment by fmulero** [comment]
Hi @conzetti

Recently @thogaw shared a PR ( #77 ) with a possible solution for these problems. I've been doing some test with version `4.3.1-debian-10-r7` and everything looks good. Could give it a try?
