### ISSUE TITLE
PGPOOL_CHILD_MAX_CONNECTIONS documentation 

### ISSUE THREAD

**Issue by foarsitter** [bitnami/bitnami-docker-pgpool#71]
The `PGPOOL_CHILD_MAX_CONNECTIONS` environment variable is mapped to `child_max_connections`. 

https://github.com/bitnami/bitnami-docker-pgpool/blob/7f622f635826cf08f8a1687516f1163cd06b9029/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L449

De documentation of this value in the readme does not match the one in the pgpool docs: 

> Specifies the lifetime of a Pgpool-II child process in terms of the number of client connections it can receive. Pgpool-II will terminate the child process after it has served child_max_connections client connections and will immediately spawn a new child process to take its place. https://www.pgpool.net/docs/42/en/html/runtime-config-connection-pooling.html#GUC-CHILD-MAX-CONNECTIONS

> The maximum number of client connections in each child process. Defaults to `0` which turns off the feature. https://github.com/bitnami/bitnami-docker-pgpool/blob/aee894a6381d873441ce89f551f4102ffb1e597e/README.md?plain=1#L255

Is my observation correct?

**Comment by carrodher** [comment]
Yep, you're right, would you like to create a PR updating the README?
