### ISSUE TITLE
https://hub.docker.com/r/bitnami/pgpool Last pushed a month ago by bitnamibot

### ISSUE THREAD

**Issue by coolincy** [bitnami/bitnami-docker-pgpool#74]
https://hub.docker.com/r/bitnami/pgpool/tags

TAG
latest
Last pushed a month ago by bitnamibot

**Comment by javsalgar** [comment]
Hi,

Thanks for opening the ticket. Yes, we are aware of it and we are fixing an issue that appeared in our daily testing. We expect to have it fixed very soon.

**Comment by carrodher** [comment]
The issue was solved and a new tag was pushed `4.2.6-debian-10-r12`; in the same way, the different rolling tags like `latest`, `4.2.6`, etc are pointing to the new tag as usual

Feel free to reopen the issue if you find any issue
