### ISSUE TITLE
Request For Documentation

### ISSUE THREAD

**Issue by robshep** [bitnami/bitnami-docker-pgpool#75]
Hi,
Firstly thank you for the efforts made in creating and maintaining this open source project - it is appreciated.

Your postgres+repmgr container is an excellent way to deploy the database stack and I was hoping this pgpool-II container will be a good fit to proxy client connections down to a volatile set of primary+secondary database servers.

Having got it working and tested it to some degree I notice that - despite repmgrd automating the underlying database relationships - pgpool still needs some manual intervention to coordinate access.

I'd like to request a little documentation for the readme to demonstrate what the typical intervention steps are.

I notice the following non-automatic scenarios:

* If the cluster topology changes, pgpool disconnects its clients until backends are stable (I.e. no SELECTS despite stable secondaries, until it can workout the primary)
* A recovered secondary needs to be re-attached to pgpool using pcp_attach_node (as long as it is listed in PGPOOL_BACKEND_NODES)
* if pgpool needs to restart, it needs the "**current**" (not _desired_) topology listed - I.e. if a secondary has died, but it was listed in PGPOOL_BACKEND_NODES then pgpool will fail to restart until it can connect to all backends
* If a secondary needs to be added to pgpool, it must be added to PGPOOL_BACKEND_NODES then restarted 
    * or within /opt/bitnami/pgpool/conf/pgpool.conf then pcp_reload_config
    * I have found this latter method then needs the new node reattaching with pcp_attach_node as well.

My request is thus to please consider if there is a better explanation (than my waffle above) in informing us non-pgpool experts what the expected behaviour is and likely manual interventions are from the configuration options available to us, or by default.

I mention this here as whilst pgpool has a lot of configuration options, only a small amount is exposed through the env vars of this container.  I'm guessing the developers here had some scenario in mind. 

Would you also be willing to make a comment regarding the FAQ on repmgr from pgpool itself: https://www.pgpool.net/mediawiki/index.php/FAQ#Can_I_use_repmgr_with_Pgpool-II.3F

For my own aims, I would like pgpool-II to just track the current state of the cluster topology.  It seems I have some work to do to get there - (potentially hooking into repmgr event_notification script for example, to rebuild pgpool's node config) so any further documentation will be gratefully received

Thanks

Rob

**Comment by juan131** [comment]
Thanks for the valuable feedback @robshep !! 

This container was created/designed to work in conjunction with the `bitnami/postgresql-repmgr` container. In particular, they were designed to be orchestrated in the [Bitnami PostgreSQL HA Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha) for Kubernetes.

The are basically 3 places where you can obtain docs about these solutions:

- Container's README.md(s): [bitnami/pgpool](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/README.md) and [bitnami/postgresql-repmgr](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/README.md) ones.
- [Chart's README.md](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/README.md).
- [Bitnami Docs syte](https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha/) generated based on [this docs repository](https://github.com/bitnami/charts-docs).

As you mentioned, there are a few non-automatic/non-documented scenarios and I agree the docs could be improved in that sense. 

Would you like to contribute by creating a PR to improve the docs? The Bitnami team will be happy to review it and provide feedback.
