### ISSUE TITLE
Incompatible psql included with pgpool

### ISSUE THREAD

**Issue by vincepower** [bitnami/bitnami-docker-pgpool#85]
### Name and Version

bitnami/pgpool:latest

### What steps will reproduce the bug?

Any deployment of the latest container contain

```
# kubectl exec --namespace=test -it postgresql-ha-pgpool-597944f785-7hvp8 -- /opt/bitnami/postgresql/bin/psql --version
psql (PostgreSQL) 10.20
```

### What is the expected behavior?

To have the latest version of pgpool use the same major version of psql as a version that is in the latest bitnami postgresql containers

### What do you see instead?

Its 4 major versions behind. docker pull bitnami/postgresql-repmgr:latest just jumped from v11 to v14 a couple months ago so being a little behind, sure, but this is really far behind.

### Additional information

See https://github.com/bitnami/bitnami-docker-postgresql/blob/master/14/debian-10/Dockerfile and https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/14/debian-10/Dockerfile

**Comment by vincepower** [comment]
This also applies to to the pgbouncer container

**Comment by vincepower** [comment]
I would submit a PR, but the latest version of postgresql-client I can find in Bitnami's existing plethora of container images is. I can't find any for v14.

Like this client in https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/prebuildfs/opt/bitnami/.bitnami_components.json
```
    "postgresql-client": {
        "arch": "amd64",
        "digest": "c47d8c57a5317ae17cff33145bc3205d06c3678a8674425c4eeb3b432eb90ebb",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "13.7.0-0"
    },
```

Though as noted above there are other postgresql packages at v14 in repmgr
From: https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/14/debian-10/prebuildfs/opt/bitnami/.bitnami_components.json
```
    "postgresql-repmgr": {
        "arch": "amd64",
        "digest": "5ddbd16c4966d611a109e71ceabaa04c1f45885c69aabe4a3a4071b82ab4ec68",
        "distro": "debian-10",
        "type": "NAMI",
        "version": "14.3.0-2"
    }
```

**Comment by dgomezleon** [comment]
Hello @vincepower,

I am creating an internal task to update this. However I can not provide an ETA.

Thanks for the feedback.
