### ISSUE TITLE
Pgpool unexpectedly crashes 

### ISSUE THREAD

**Issue by garciabruno** [bitnami/bitnami-docker-pgpool#86]
### Name and Version

bitnami/pgpool@sha256:8c18769a7df6880a4e98bbe614d7910368a99d3af62c0d62c9da26d24f856c2b

### What steps will reproduce the bug?

We're not sure how to reproduce the error, connections and queries run just fine until pgpool unexpectedly crashes.

### What is the expected behavior?

Not to crash.

### What do you see instead?
```
2022-06-09 13:53:22.968: main pid 1: LOG:  shutting down by signal 15                                                                                                                         
2022-06-09 13:53:22.968: main pid 1: LOG:  terminating all child processes   
```
### Additional information

1. Our backend databases are managed by RDS (including replication)
2. Users connecting to pgpool are provided via environment variables and have permissions to their belonging database, but can't connect to any other database
3. Memory cache is explicitly disabled
4. CPU and RAM are sufficient in the server that pgpool is running at

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami pgpool container image itself but about how the application or environment is being used/configured. 

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
