### ISSUE TITLE
Docker Swarm Cluster Failover Stability

### ISSUE THREAD

**Issue by tengcomplex** [bitnami/bitnami-docker-pgpool#87]
### Name and Version

bitnami/pgpool:4.3.2-debian-11-r6

### What steps will reproduce the bug?

1. Set up cluster.
2. Simulate failures.

### What is the expected behavior?

HA PostgreSQL Pgpool-II cluster on Docker Swarm dealing with exceptions and failures properly.

### What do you see instead?

Doesn't deal with exceptions and failures properly.

## Synopsis
Summary of the experiences running an HA PostgreSQL cluster with pgpool, streaming replication and repmgr on a Docker
Swarm cluster.
Even though there is a ready to run docker-compose-yml example published, it seems the pgpool/repmgr/postgresql cluster
is not optimized and tested to run well in swarm mode.
Some problems we encountered are explained further down.

## Setup
HA setup, with 2 postgresql-repmgr and 2 pgpool instances.
Basically we run the "default" Docker Compose setup as described in 
[README](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/README.md).

Versions:
* Linux 5.13.0-35-generic 20.04.1-Ubuntu
* Docker 20.10.13, build a224086
* bitnami/pgpool:4.3.2-debian-11-r6
* bitnami/postgresql-repmgr:14.3.0-debian-11-r4

Platform: Docker Swarm
* Server 0 (Manager): pg-0, pgpool.1
* Server 1 (Worker): pg-1, pgpool.2

In fact there are more worker nodes and we are planing to run server 1 as a manager as well but for the sake of 
a simplified description let's assume such a setup.

Generally the system runs fine. 
Starts and performs alright, pg replication and pgpool load balancing is doing what it should do.

Things get interesting when exceptions are to be handled.
If a pg service fails as standby, it should just restart and become a standby again.
If it fails as a primary, the other pg should take over as primary, the failed service should become a standby after 
restart.

A failure of a pg service can be simulated by various docker operations.
* `docker service update --force servicename`
   Causes immediate restart of all instances of the service.
* `docker stop containername`
  Causes a restart of the container after configured restart-delay.
* `docker service scale servicename=num`
  Causes decrease/increas the number of instances, value can be 0 to remove pg-N for example.

### 1) Just one node available
When shutting down one node, regardless of it's state, the cluster doesn't deal with it properly.
The pgpool instances run in some kind of restart loop. It appears the health checks of the backend nodes are running in 
timeouts so that the pgpool instances are considered unhealthy after a while.

When running the cluster in swarm mode but on a single manager only, it works fine. 
The dead node is removed, pgpool doesn't restart, the cluster is usable.
Only in a multi node swarm docker seems to resolve internal hostnames in a different way.

This might be caused by the problems described in bitnami-docker-pgpool issue [#79](https://github.com/bitnami/bitnami-docker-pgpool/issues/79).
Instead of trying the workaround with an internal DNS Server in the pgpool container as described by @tusooa in this [comment](https://github.com/bitnami/bitnami-docker-pgpool/issues/79#issuecomment-1104485175), we tried to adjust the timeouts in pgpool_healthcheck function of [libpgpool.sh](https://github.com/bitnami/bitnami-docker-pgpool/blob/81a851c0f4f0fdeb2045c299ccb25fbd97c4e051/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh#L292) script and adjusted healthcheck attributes of pgpool container in docker-compose.yml to interval: 10s, timeout: 45s, retries: 15.

```
pgpool_healthcheck() {
    info "Checking pgpool health..."
    local backends
    backends="$(PGCONNECT_TIMEOUT=45 PGPASSWORD="$PGPOOL_POSTGRES_PASSWORD" psql -U "$PGPOOL_POSTGRES_USERNAME" \
        -d postgres -h "$PGPOOL_TMP_DIR" -p "$PGPOOL_PORT_NUMBER" -tA -c "SHOW pool_nodes;" || true)"
    info "backends:"$backends
    if [[ "$backends" ]]; then
        # look up backends that are marked offline
        for node in $(echo "${backends}" | grep "down" | tr -d ' '); do
            IFS="|" read -ra node_info <<< "$node"
            local node_id="${node_info[0]}"
            local node_host="${node_info[1]}"
            info "node_id:"$node_id", node_host:"$node_host
            local node_state="$(PGCONNECT_TIMEOUT=3 PGPASSWORD="${PGPOOL_POSTGRES_PASSWORD}" psql -U "${PGPOOL_POSTGRES_USERNAME}" \
                -d postgres -h "${node_host}" -p "${PGPOOL_PORT_NUMBER}" -tA -c "SELECT 1" || true)"
            info "node_state:"$node_state
            if [[ "$node_state" == 1 ]]; then
                # attach backend if it has come back online
                info "Attaching "$node_id
                pgpool_attach_node "${node_id}"
            fi
        done
    else
        return 1
    fi
}
```

We are currently testing this and so far this seems to work even though the phase before pgpool updates the state of the
unavailable node takes a little longer due to longer timeouts.

### 2) Immediate standby restart
If the standby node is restarted by a `docker service update --force servicename` it comes back instantly, the pgpool 
instances however are logging lots of messages like this.
```
2022-06-27 13:39:50.581: child pid 484968: ERROR:  unable to read message kind
2022-06-27 13:39:50.581: child pid 484968: DETAIL:  kind does not match between main(0) slot[0] (52)
```

In this phase things appear a bit erratic.
Existent connection are still alive, at least for a while.
The cluster is having trouble to accept new connections.
After a while pgpool container are considered unhealthy and restarting, after that all is good again.
Some hits in [pgpool-general](https://www.sraoss.jp/pipermail/pgpool-general/) suggesting auth problems or insufficient max_connections, but so far no clue what happens 
here exactly.

This doesn't seem to occur upon a restart of the primary pg service.

### 3) Failover with restart timing
When the postgresql-repmgr instance comes up during the promotion of a standby we sometimes observe a inconsistent state 
of the the cluster.
In most cases the restart is so quick that a failover doesn't occur with the default settings.
Since there is no guarantee for that a [restart-policy delay](https://docs.docker.com/compose/compose-file/deploy/#restart_policy) can reduce the risk of a server restart during a failover.
It cannot eliminate the risk though. 

Looking on "SHOW POOL_NODES" we saw two scenarios.
1) Replication broken<br>
   On both pgpool instances for one pg node status/pg_status both "up", role/pg_role "standby"/"primary" and a replication_delay greater 0 which grows over time. The other pg node role/pg_role "primary"/"primary" with no replication_delay.
2) Replication crossed<br>
   On both pgpool instances for one pg node status/pg_status both "up", role/pg_role "standby"/"primary" and a replication_delay is 0.
   For the other pg node it shows role/pg_role "primary"/"standby" and also replication_delay is 0.
   When connecting to a pgpool SELECT statements work but database modifications are responded with an error.

See bitnami-docker-postgresql-repmgr issue [#113](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/113).
In this issue it is suggested to fix the state of the cluster manually which lead to the idea to do so by a script.

Idea:
* Run script on nodes with pg pgpool nodes periodically.
* Check "SHOW POOL_NODES" and parse output.
* If seeing one of the two scenarios above take action and restart a "broken" pg instance.

**Very rough experimental scripting, use on your own risk!** 
```
#!/bin/bash

declare -A crossedPgServerInstances
pgServerInstanceCount=0

function restartPgserverInstance {
  echo "Get pgserverInstance for "$1
  local pgserverInstance=($(docker ps --filter "name=$1" --format "{{.Names}}" | head -n 1))
  echo "restart pgserverInstance "$pgserverInstance
  docker stop $pgserverInstance
}

function restartPgpoolInstances {
  echo "Restarting pgpool instances"
  docker ps --filter "name=pgpool" --format "{{.Names}}" | xargs -n1 docker stop
}

pgpoolInstances=($(docker ps --filter "name=pgpool" --format "{{.Names}}"))
for pgpoolInstance in "${pgpoolInstances[@]}" ; do
  echo "pgpool status "$pgpoolInstance
  mapfile -t pgpoolInstanceData < <( docker exec $pgpoolInstance psql postgresql://user:password@localhost -t -A -c "SHOW POOL_NODES" | \
    awk 'BEGIN {FS="|"} {print $2" "$4" "$5" "$7" "$8" "$11}' )
  for i in "${pgpoolInstanceData[@]}" ; do
    echo "pgpoolInstanceData:"$i
    pgServerInstanceCount=${#pgpoolInstanceData[@]}
    read -r -a pidt <<< "$i"
    allUp=false
    if [ "${pidt[1]}" == "up" ] && [ "${pidt[2]}" == "up" ] ; then
      allUp=true
    fi
    replicationDelay=${pidt[5]}
    if [ $allUp = true ] && [ "${pidt[3]}" == "standby" ] && [ "${pidt[4]}" == "primary" ] && [ "$replicationDelay" -gt "100" ] ; then
      echo "Candidate "${pidt[0]}
      restartPgserverInstance ${pidt[0]}
      exit 0
    fi
    if [ $allUp = true ] && [ "${pidt[3]}" == "standby" ] && [ "${pidt[4]}" == "primary" ] && [ "$replicationDelay" -eq "0" ] ; then
      echo "Candidate "${pidt[0]}" crossed"
      crossedPgServerInstances[${pidt[0]}]=1
    elif [ $allUp = true ] && [ "${pidt[3]}" == "primary" ] && [ "${pidt[4]}" == "standby" ] && [ "$replicationDelay" -eq "0" ] ; then
      echo "Candidate "${pidt[0]}" crossed"
      crossedPgServerInstances[${pidt[0]}]=1
    fi
  done
  echo "--------------------------------------"
done

crossedPgServerCount=${#crossedPgServerInstances[@]}
echo "pgServerInstanceCount:"$pgServerInstanceCount", crossedPgServerCount:"$crossedPgServerCount
echo "crossedPgServerInstances:"${!crossedPgServerInstances[@]}
if [ "$crossedPgServerCount" -eq "$pgServerInstanceCount" ] ; then
  restartPgpoolInstances
fi
```
We are currently testing this.

## Questions
* Docker Swarm is not considered as a stable platform? 
   * If not, are there any efforts to change that?
   * We got a little surprised by the [comment](https://github.com/bitnami/bitnami-docker-pgpool/issues/45#issuecomment-754142395) of @beltran-rubo.  
     Shouldn't it be mentioned more prominently in the README files?
* Is there some known race-condition as in "1) Just one node available" during node start during promotion?
    * Would a configurable PGCONNECT_TIMEOUT in pgpool_healthcheck  be a good idea maybe?
* Any idea what might be the cause for "2) Immediate standby restart" behaviour?
* Would a self-fix for "3) Failover with restart timing" within pgpool make sense maybe?

Any thoughts in this regard appreciated.
If it would help to split the observations in more specific issues, please advise.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
